### ISSUE TITLE
For PHP 5.2

### ISSUE THREAD

**Issue by dschultzca** [vinny/recaptcha-2-phpbbmod#2]
Hi: Are you aware of a recaptcha v2 mod that will run with PHP 5.2?
Or is there a few code changes I could make to this project to support 5.2?
Thanks

**Comment by vinny** [comment]
This MOD works in 5.2.

Must work at minimum required for phpBB 3.0 (PHP 4.3.3+ (>=4.3.3, >4.4.x, >5.x.x, >6.0-dev (compatible)))

**Comment by dschultzca** [comment]
Okay.
Would you have any idea what would cause these error messages?

Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /var/www/.../forum/includes/captcha/plugins/phpbb_recaptcha_new_plugin.php on line 294
 Warning: Unexpected character in input: '\' (ASCII=92) state=1 in /var/www/.../forum/includes/captcha/plugins/phpbb_recaptcha_new_plugin.php on line 294
 Parse error: syntax error, unexpected T_STRING in /var/www/prizolovy/data/www/.../forum/includes/captcha/plugins/phpbb_recaptcha_new_plugin.php on line 294

My brief search suggested that it's related to the use of namespace not supported by PHP v5.2.
Also I'm using phpBB 3.0.10.
Thanks

**Comment by vinny** [comment]
Indeed, namespaces are only available as of PHP [5.3.0+](http://php.net/manual/en/language.namespaces.rationale.php)

**Comment by vinny** [comment]
I added this information to [README](https://github.com/vinny/recaptcha-2-phpbbmod/blob/master/README.md).

So I recommend that you upgrade the PHP version to at least 5.3

**Comment by dschultzca** [comment]
Unfortunately for me I have no control over the PHP version implemented.
Thanks

**Comment by vinny** [comment]
You can contact the support of your hosting and ask to update the PHP version.
